title: zurg3's blog
# email: your-email@example.com
author: zurg3
timezone: Europe/Moscow
description: >- # this means to ignore newlines until "baseurl:"
  A simple blog powered by Jekyll and GitHub Pages
baseurl: "/jekyll-blog/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: zurg3
github_username:  zurg3
facebook_username: zurg3
instagram_username: zurg3
youtube_username: zurg3real
mastodon:
- username: zurg3
  instance: mastodon.social

header_pages:
  - editor.html
  - telegram.html
  - about.md

# Minima date format
minima:
  # date_format: "%b %-d, %Y" # default date format
  date_format: "%d.%m.%Y"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
